print "hello Robot(Reply)!"
print "am shedrack by name!, am your maker!"
print " welcome to the first stage of your system diagnosis!"
print "i hope you follow the first rule of robotics"
print " let us begin!"
print " You have A 13 mp mini camera installed of the main unit of your body for Robotic vision!"
print "You have parts for movement"
